### ISSUE TITLE
Quest Industrial Craft 2 Insulated Copper Cable: not triggering reward

### ISSUE THREAD

**Issue by stijndp** [NordicGamerFE/Ocean-Outlast#21]
Version
Expert 48 HF1
From ATLauncher no custom mods.

Description:
Crafted 12 Insulated Copper Cable (IC2) with the recipe Rubber (IC2) + Copper Cable (IC2).
The quest for Insulated Copper Cable requires 8 Insulated Copper Cable but it doesn't trigger.
Reloading world/game didn't help.

![image](https://user-images.githubusercontent.com/29801608/88108005-6785fd00-cba8-11ea-9433-73f89645b02f.png)
![image](https://user-images.githubusercontent.com/29801608/88108014-6c4ab100-cba8-11ea-8b7a-096e626ad3a0.png)

Bug is in the quest file.
I'll pull request the fix.

![image](https://user-images.githubusercontent.com/29801608/88108030-72409200-cba8-11ea-946d-ab50ab6e2af0.png)

**Comment by NordicGamerFE** [comment]
Pull Request for quests is pointless i start working on quests right after i push updates. this has been fixed for the next update

**Comment by TheSavageYarloo** [comment]
I still have this same issue in version V66.1
Is there a way to fix it by myself? I tried to craft it with the second recipe (not the rubber from IC2) in the crafting menu and in a crafting table. Even giving them myself in a second world doesnt work :l

I'll take any advice, thx!
